site_name: ICEpy4D
repo_url: https://github.com/franioli/icepy4d
site_author: Francesco Ioli

theme:
  name: material
  palette:
    primary: indigo
  font:
    text: Open Sans
  features:
    - navigation.path
    - navigation.footer

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folder
          options:
            show_source: false

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting started: getting_started.md
